#pragma once

#include "AssignEntityFactory.h"
#include "CallEntityFactory.h"
#include "ConstantEntityFactory.h"
#include "EntityFactory.h"
#include "IdentEntityFactory.h"
#include "IfEntityFactory.h"
#include "IntEntityFactory.h"
#include "PrintEntityFactory.h"
#include "ProcedureEntityFactory.h"
#include "ReadEntityFactory.h"
#include "StmtEntityFactory.h"
#include "VariableEntityFactory.h"
#include "WhileEntityFactory.h"
