#pragma once

#include "AffectsClause.h"
#include "CallsClause.h"
#include "CallsTClause.h"
#include "Clause.h"
#include "FollowsClause.h"
#include "FollowsTClause.h"
#include "ModifiesClause.h"
#include "NextClause.h"
#include "ParentClause.h"
#include "ParentTClause.h"
#include "PatternClause.h"
#include "UsesClause.h"
#include "NextTClause.h"
#include "WithClause.h"
