name: cpplint
on: 
    push:
        branches:
        - master
        - pkb/optimisations
    pull_request:
        branches:
        - master
        - pkb/optimisations
    workflow_dispatch: {}
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --exclude=./Team05/Code05/src/autotester_gui --exclude=./Team05/Code05/src/autotester --recursive --filter=-legal/copyright,-build/header_guard,-runtime/references ./Team05/Code05/src
