# Runs the python script for analysing query statistics and 
# directly adds the updated statistics as a commit to your PR
name: Update query statistics

on:
  workflow_dispatch: {}

jobs:
  run_script: 
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        # persist-credentials: false # otherwise would use github token instead of PAT
        fetch-depth: 0 # otherwise there would be errors pushing refs to the destination repository
        ref: ${{ github.ref }}

    # Use cache so that we don't have to rebuild autotester
    # and run system tests again
    - name: Restore cached out.xml files
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/Team05/Tests05/out
        key: ${{ runner.os }}-out-xml-cache-${{ hashFiles('**/Tests05/out/**') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run query statistics analysis
      run: |
        python ${{github.workspace}}/Team05/Tests05/out_analysis.py 
    
    - name: Commit query statistics files
      run: |
        git config --local user.email "39623254+aizatazhar@users.noreply.github.com"
        git config --local user.name "aizatazhar"
        git commit -a -m "Update out_analysis files"
    
    # Sadly need to use a PAT otherwise the on push workflows
    # won't be triggered when the commit is added to the PR
    # https://github.com/orgs/community/discussions/25702
    # But since we don't own the organisation, we can't
    # generate a PAT with write access
    # Alternative is to close and reopen the PR to
    # trigger the workflows
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}