#include "ArgumentFactory.h"
#include "AttrRefFactory.h"
#include "ExactExpressionArgFactory.h"
#include "IdentArgFactory.h"
#include "SynonymArgFactory.h"
#include "WildcardExpressionArgFactory.h"
#include "WildcardFactory.h"
